<?php

namespace AppBundle\Repository;

/**
 * BlocDroiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlocDroiteRepository extends \Doctrine\ORM\EntityRepository
{
}
