<?php

namespace AppBundle\Repository;

/**
 * BlocGaucheRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlocGaucheRepository extends \Doctrine\ORM\EntityRepository
{
}
