<?php

namespace AppBundle\Repository;

/**
 * ChampImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChampImageRepository extends \Doctrine\ORM\EntityRepository
{
}
