<?php

namespace AppBundle\Repository;

/**
 * ChampTitreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChampTitreRepository extends \Doctrine\ORM\EntityRepository
{
}
