<?php

namespace AppBundle\Repository;

/**
 * ChampEncartRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChampEncartRepository extends \Doctrine\ORM\EntityRepository
{
}
