<?php

namespace AppBundle\Repository;

/**
 * ChampActualiteContentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChampActualiteContentRepository extends \Doctrine\ORM\EntityRepository
{
}
