<?php

namespace AppBundle\Repository;

/**
 * ChampDiaporamaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChampDiaporamaRepository extends \Doctrine\ORM\EntityRepository
{
}
