<?php

namespace AppBundle\Repository;

/**
 * ChampFormulaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChampFormulaireRepository extends \Doctrine\ORM\EntityRepository
{
}
