<?php

namespace AppBundle\Repository;

/**
 * ChampMapRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChampMapRepository extends \Doctrine\ORM\EntityRepository
{
}
