<?php

namespace AppBundle\Repository;

/**
 * ChampEmbarqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChampEmbarqueRepository extends \Doctrine\ORM\EntityRepository
{
}
