<?php

namespace AppBundle\Repository;

/**
 * ChampSlideContentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChampSlideContentRepository extends \Doctrine\ORM\EntityRepository
{
}
