<?php

namespace AppBundle\Repository;

/**
 * ChampSlideRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChampSlideRepository extends \Doctrine\ORM\EntityRepository
{
}
