<?php

namespace AppBundle\Repository;

/**
 * ChampTexteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChampTexteRepository extends \Doctrine\ORM\EntityRepository
{
}
