<?php

namespace AppBundle\Repository;

/**
 * CompteDossiersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompteDossiersRepository extends \Doctrine\ORM\EntityRepository
{
}
