<?php

namespace AppBundle\Repository;

/**
 * DiaporamaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DiaporamaRepository extends \Doctrine\ORM\EntityRepository
{
}
