<?php

namespace AppBundle\Repository;

/**
 * SousPageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SousPageRepository extends \Doctrine\ORM\EntityRepository
{
}
