<?php

namespace AppBundle\Repository;

/**
 * SousPageLienRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SousPageLienRepository extends \Doctrine\ORM\EntityRepository
{
}
